### ISSUE TITLE
location issue

### ISSUE THREAD

**Issue by shabeebpm** [AmNe5iA/Device-Wipers#1]
Hello, 
Do i need to specify the location to wipe the disk ?

**Comment by AmNe5iA** [comment]
What do you mean by location?

**Comment by shabeebpm** [comment]
I meant the target disk

**Comment by AmNe5iA** [comment]
No. The scripts are designed to wipe the whole device. Not a single partition or a single file.

**Comment by shabeebpm** [comment]
thank you
